%%{init: {'gantt': {'barHeight': 35, 'barGap': 6, 'topPadding': 60, 'sidePadding': 75, 'fontSize': 32}}}%%
gantt
    title Retail Rollup Project
    dateFormat  YYYY-MM-DD
    todayMarker off

    section Phase 1
        Fact Find                       :a1, 2026-02-19, 14d
        Agree Seed Files                :a2, 2026-02-19, 7d
        Clean up Jan tech debt          :a3, 2026-02-14, 21d
        Explore Hiscox tech             :a4, after a2, 14d

    section Phase 2
        Define business structure       :b1, 2026-03-05, 2d
        GC playbacks                    :b2_a, after b1, 7d
        Pre-modelling process           :b2, after b1, 21d
        Post-modelling process          :b3, after b2, 21d

    section Phase 3
        Replicate GC process gaps       :c1, after b3, 14d

    section Milestones
        Phase 1 End                     :milestone, m1, after a4, 0d
        Obtain 2025 datasets            :crit, after a2, 1d
        Obtain April Data               :crit, 2026-04-14, 1d
