%%{init: {
  'gantt': {
    'barHeight': 45, 
    'barGap': 10, 
    'topPadding': 60, 
    'sidePadding': 75, 
    'fontSize': 38, 
    'sectionFontSize': 32
  }
}%%

gantt
    title Retail Rollup Project
    dateFormat  YYYY-MM-DD

    section Phase 1
    Fact Find                       :done, a1, 2026-02-19, 14d
    Agree Seed Files                :done, a2, 2026-02-19, 7d
    Explore Hiscox tech             :done, a4, after a2, 7d
    Clean up Jan tech debt          :crit, a3, 2026-02-14, 21d
    Clean up Jan post-modelling extended :active, a5, after a3, 30d
    Phase 1 End                     :vert, v1, 2026-03-05, 0d

    section Phase 2
    Define business structure       :active, b1, 2026-03-05, 10d
    GC playbacks                    :active, b2, after v1, 7d
    Create validation tools EU/UK   :active, b3, after v1, 20d
    Send validation tool to EU      :milestone, b4, after b3, 2026-03-25
    Audit & review GC checks        :b5, after v1, 14d
    
    section Blocked/At Risk
    Databricks access [TOO SLOW DON'T USE]    :milestone, crit, m1, 2026-03-01, 0d
    Corporate git [SLOW]            :milestone, crit, m2, 2026-03-17, 0d
    UK Prop + FA Data [SLOW]        :milestone, crit, m3, 2026-03-12, 0d
    LM Fine Art Data [AGREE]        :milestone, crit, m4, 2026-03-20, 0d

    section Phase 2 (continued)
    Begin dry run 2025 datasets     :milestone, m5, 2026-04-10, 0d
    Dry run 2025                    :dr1, 2026-03-28, 10d
    Obtain 2026 data                :d1, 2026-05-01, 10d
Fat Built-in [NEEDED] :f1,  after m5, 20d
    Phase 2 End                     :vert, v3, 2026-05-01, 0d

    section Phase 3
    Post-modelling process          :b6, after d1, 30d
    Confirm process runs            :milestone, m6, after b6, 0d
    Handover to analyst             :handover1, after b6, 30d
    Phase 3 END                     :vert, v4, 2026-06-30, 0d
