from __future__ import annotations

from enum import StrEnum


class RawCol(StrEnum):
    Analysis = "Analysis"
    ExposureAttribute = "ExposureAttribute"
    CatalogTypeCode = "CatalogTypeCode"
    EventID = "EventID"
    ModelCode = "ModelCode"
    YearID = "YearID"
    GroundUpLoss = "GroundUpLoss"

    anlsid = "anlsid"
    yearid = "yearid"
    eventid = "eventid"
    loss = "loss"

    ModelID = "ModelID"
    Event = "Event"
    Year = "Year"
    Day = "Day"

    ModelOccurrenceYear = "ModelOccurrenceYear"
    ModelOccurrenceDate = "ModelOccurrenceDate"
    RegionPerilID = "RegionPerilID"
    SubRegionPeril = "SubRegionPeril"
    SubRegionPerilID = "SubRegionPerilID"
    AIRBlend = "AIRBlend"
    RMSBlend = "RMSBlend"

    currency_code = "currency_code"
    rate_date = "rate_date"
    rate = "rate"
    factor = "factor"
    occ_year = "occ_year"
    max_rank = "max_rank"


class Col(StrEnum):
    vendor = "vendor"
    analysis_id = "analysis_id"
    modelled_lob = "modelled_lob"
    modelled_peril = "modelled_peril"
    rollup_lob = "rollup_lob"
    rollup_peril = "rollup_peril"
    region_peril_id = "region_peril_id"
    blend_subregion_peril_id = "blend_subregion_peril_id"
    cds_cat_class_name = "cds_cat_class_name"
    class_ = "class"
    office = "office"
    currency = "currency"
    model_code = "model_code"
    year_id = "year_id"
    event_id = "event_id"
    loss = "loss"
    base_model = "base_model"
    base_model_loss = "base_model_loss"
    metric = "metric"
    ep_type = "ep_type"
    return_period = "return_period"
    selection_priority = "selection_priority"
    is_dialsup = "is_dialsup"
    is_euws = "is_euws"
    risklink_loss = "risklink_loss"
    verisk_loss = "verisk_loss"
    risklink_weight = "risklink_weight"
    verisk_weight = "verisk_weight"
    target_loss = "target_loss"
    uplift_factor_on_base_model = "uplift_factor_on_base_model"
    sub_region_peril_id = "sub_region_peril_id"
    sub_region_peril = "sub_region_peril"
    rnk = "rnk"
    rp = "rp"
    rp_bucket = "rp_bucket"
    forecast_date = "forecast_date"
    forecast_factor = "forecast_factor"
    forecast_factor_raw = "forecast_factor_raw"
    target_currency = "target_currency"
    fx_rate_date = "fx_rate_date"
    fx_rate = "fx_rate"
    model_event_id = "model_event_id"
    event_day = "event_day"
    model_occurrence_date = "model_occurrence_date"
    risklink_event_day = "risklink_event_day"
    row_count = "row_count"
    loss_sum = "loss_sum"
    missing_model_event_id = "missing_model_event_id"
    missing_model_event_day = "missing_model_event_day"
    original_ylt_loss = "original_ylt_loss"
    original_ylt_loss_blended = "original_ylt_loss_blended"
    original_ylt_loss_blended_gbp = "original_ylt_loss_blended_gbp"
    original_ylt_loss_blended_gbp_forecast = "original_ylt_loss_blended_gbp_forecast"
    original_ylt_loss_blended_gbp_forecast_euws_raw = "original_ylt_loss_blended_gbp_forecast_euws_raw"
    original_ylt_loss_blended_gbp_forecast_euws = "original_ylt_loss_blended_gbp_forecast_euws"
    euws_factor_raw_source = "euws_factor_raw_source"
    euws_factor_raw = "euws_factor_raw"
    euws_factor = "euws_factor"
    euws_override_max_rank = "euws_override_max_rank"
    euws_override_factor = "euws_override_factor"
    euws_override_applied = "euws_override_applied"
    dialsup_original_ylt_loss = "dialsup_original_ylt_loss"
    dialsup_loss_gbp = "dialsup_loss_gbp"
    dialsup_loss_gbp_forecast = "dialsup_loss_gbp_forecast"


class FanoutCol(StrEnum):
    ModelEventID = "ModelEventID"
    ModelYear = "ModelYear"
    CurrencyCode = "CurrencyCode"
    ModelYOA = "ModelYOA"
    ModelGrossLoss = "ModelGrossLoss"
    ModelInwardsReinstatement = "ModelInwardsReinstatement"
    ModelEventDay = "ModelEventDay"
    LossClassName = "LossClassName"
