version: 2

sources:
  - name: reference
    schema: reference
    tables:
      - name: lobs
      - name: air_events
      - name: euws_rate_factors
      - name: blending_factors
      - name: forecast_factors_with_lobs_to_apply
      - name: fx_rates
      - name: flood_rl22_model_events

  - name: core
    schema: main
    tables:
      - name: dim_region_perils
      - name: dim_rl_analysis

  - name: catmodel
    schema: catmodel
    tables:
      - name: risklink_ylt
      - name: verisk_ylt
      - name: risklink_ep
      - name: verisk_ep
